use oddawanie

DELETE FROM POZYCJE
DELETE FROM KSIAZKI
DELETE FROM WYDAWCY
DELETE FROM PARAGONY
DELETE FROM PRACOWNICY
DELETE FROM KSIEGARNIE
DELETE FROM ADRESY
DELETE FROM GATUNKI
DELETE FROM AUTORZY
DELETE FROM LUDZIE

DROP TABLE POZYCJE
DROP TABLE KSIAZKI
DROP TABLE WYDAWCY
DROP TABLE PARAGONY
DROP TABLE PRACOWNICY
DROP TABLE KSIEGARNIE
DROP TABLE ADRESY
DROP TABLE GATUNKI
DROP TABLE AUTORZY
DROP TABLE LUDZIE
