use oddawanie

--UPDATE 1
SELECT *
FROM AUTORZY
JOIN LUDZIE ON AUTORZY.PESEL = LUDZIE.PESEL

UPDATE LUDZIE
SET PESEL = '12343219072'
WHERE PESEL = '92030456789'

SELECT *
FROM AUTORZY
JOIN LUDZIE ON AUTORZY.PESEL = LUDZIE.PESEL
/**/
--UPDATE 2
/*
SELECT *
FROM PRACOWNICY
JOIN LUDZIE ON PRACOWNICY.PESEL = LUDZIE.PESEL

UPDATE LUDZIE
SET PESEL = '12343219073'
WHERE PESEL = '62345678911'

SELECT *
FROM PRACOWNICY
JOIN LUDZIE ON PRACOWNICY.PESEL = LUDZIE.PESEL*/
--UPDATE 3

/*
SELECT * 
FROM KSIAZKI
JOIN GATUNKI ON KSIAZKI.ID_GATUNKU = GATUNKI.ID_GATUNKU 

UPDATE GATUNKI
SET NAZWA = 'STRASZNE FILMY'
WHERE ID_GATUNKU = '529434'

SELECT * 
FROM KSIAZKI
LEFT JOIN GATUNKI ON KSIAZKI.ID_GATUNKU = GATUNKI.ID_GATUNKU
*/
--DELETE 1

/*SELECT *
FROM WYDAWCY
JOIN ADRESY ON WYDAWCY.ID = ADRESY.ID

DELETE WYDAWCY
WHERE ID = 8

SELECT *
FROM WYDAWCY
JOIN ADRESY ON WYDAWCY.ID = ADRESY.ID
*/
--DELETE 2
/*
SELECT *
FROM POZYCJE
JOIN PARAGONY ON POZYCJE.NUMER_PARAGONU = PARAGONY.NUMER_PARAGONU

DELETE PARAGONY
WHERE NUMER_PARAGONU = 3

SELECT *
FROM POZYCJE
JOIN PARAGONY ON POZYCJE.NUMER_PARAGONU = PARAGONY.NUMER_PARAGONU*/

--DELETE 3
/*
SELECT *
FROM KSIEGARNIE
JOIN PARAGONY ON KSIEGARNIE.NAZWA_KSIEGARNI = PARAGONY.NAZWA_KSIEGARNI

DELETE PARAGONY
WHERE NAZWA_KSIEGARNI = 'Ksia¿ki Wojtka, inc. 1'

SELECT *
FROM KSIEGARNIE
JOIN PARAGONY ON KSIEGARNIE.NAZWA_KSIEGARNI = PARAGONY.NAZWA_KSIEGARNI
*/



